language: node_js
node_js:
- '6'
notifications:
  slack:
    secure: e2BJX9uKArsAOKvrsbEerN9fo5dPIrDnsfbbohudO7sxqej5Nn+mfVclCYsBei885IXQS6jTr8KC4fHIONcGSpGMZgARA1/Wy672jJpSv2TeLqMnExwLYW8nQYMOd/KeJX6ShdLW+SW9Vzkn9Hy5sMrOrZGOxnyAInxm1yPkq+chOk+64Pr30IoCWN1qsc2VNroMivHWU0FOk+8ZBdZ3PJBIIrOGz7BuMC0R3EjBX2EmEBCbkoM0F7uUPJvgSaa65KKkgePD6wJWqQ7QzGxhLt5v9Tb83adc1RkP0wBnSRxrzESiE+Tufabuqr0+7O5L05SSUckw4ivK1T4x2vo60f+VoiHzUnnVARtbGMVZ0jx6As3K6tXGwWoHfUBeX7OW3uo8Acn7c/TlvZpvE2ArArkFdB7xCbJ0pZuUy7/fXogyte15v7T/fVBq1/ONTG5qjnW7H3w2ipHoD4fkOoL78Duysm6jTSYXM2YSY7p3QljuGecsM3MJS/jzDteBmwC0v+pN39w3whIjgGSRm7zr0bkryI1avkgO6LRT4JkeQ5zs6/y6PygShG85Cq9zvCDxirU6KiTCA+lL8XprUsFtdFetfe4M7Z+r+TX5mkBJvPDMERb10eJ8HCD+Fo9YRFsG7AeKYtCsjTnmYjEpHMXDgPZ3N1qADd3mBwOIFhjyLCg=
