language: node_js
node_js:
- '6'
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: WcQHHPnjIU4dFa1zrjc02xMYksgE0RhdtA4E2uYLLvGYuHhU+0NIP5Wv+7Z0+BWnxoz8FWb5ww42bkX+5WLGCXxuJQC0DPhrr+VBsDDvuJkNcZh4lOiKQvOtnaHBS7jEqOOe0XxrVcgfBrsSsaflGMIxB3S2rajr+a51nZPUXGNZFIQs3c490MqPPX+7mDZQO88IRh41I0quCV53ABdmJxrBjqn9tsXdAiWOePoqe22TRiywgyqd1ZvsHkmSTaZ2UYhfsuIkcY2yAV+53zAMNlOgsFTivZ3diRwcJoNp80IxctQv0uw3XOJ1LPQ3hohhVUZQ5rHdLDGqvNZ9piwb8RcKofwMFSj6VNClP470B4N9Jf5AoHkil23qE9gJnKiA4wMT4gYyUrPOJpHZOWo4cdmpq4g29vWUH01w4dmqkccD+/ZQEPngjAdUJVVN+7T+yPMXxMd3Hu708sM9GahWpbikIpOraTNccRiWmuaHBCuMcz+hemrgsiUTplMb4uqKpVcSRodhuZYMTelobf9bsJbEPhdSh6fgB7M6NzuLekBto0ru9cXTNer8bBZ5UEqLSpPuvysg8APclWkfMmD9H6etC1YARCtwsWzOehpWhJw7tuz2IU7Ew4OyyDaCuCbIWYSrvXQm7Gr/0+E6NS17qRgAQkCIRiSn6xjbM+brmMk=

